In [37]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
str1 = 'sunshine state enjoy sunshine'
str2 = 'brown fox jump high, brown fox run'
str3 = 'sunshine state fox run fast'

corpus = [str1, str2, str3]
corpus

['sunshine state enjoy sunshine',
 'brown fox jump high, brown fox run',
 'sunshine state fox run fast']

In [39]:
bow_vectorizer = CountVectorizer()
bow = bow_vectorizer.fit_transform(corpus)

features = bow_vectorizer.get_feature_names()
vocabulary = bow_vectorizer.vocabulary_
vectors = bow.toarray()

i = 0
for i in range(0, len(vectors)):
    print('string', i, ':', vectors[i])
    i =+ 1

string 0 : [0 1 0 0 0 0 0 1 2]
string 1 : [2 0 0 2 1 1 1 0 0]
string 2 : [0 0 1 1 0 0 1 1 1]

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [40]:
bow = pd.DataFrame(bow.toarray(), columns = features)
bow

   brown  enjoy  fast  fox  high  jump  run  state  sunshine
0      0      1     0    0     0     0    0      1         2
1      2      0     0    2     1     1    1      0         0
2      0      0     1    1     0     0    1      1         1

In [41]:
tfidf_vectorizer = TfidfTransformer()
var = tfidf_vectorizer.fit_transform(bow)
idf = pd.DataFrame({'feature':features, 'idf':tfidf_vectorizer.idf_})
idf

    feature       idf
0     brown  1.693147
1     enjoy  1.693147
2      fast  1.693147
3       fox  1.287682
4      high  1.693147
5      jump  1.693147
6       run  1.287682
7     state  1.287682
8  sunshine  1.287682

In [42]:
tf_idf = pd.DataFrame(np.round(var.toarray(),3) ,columns=features)
tf_idf

   brown  enjoy   fast    fox   high   jump    run  state  sunshine
0  0.000  0.507  0.000  0.000  0.000  0.000  0.000  0.386     0.771
1  0.671  0.000  0.000  0.510  0.335  0.335  0.255  0.000     0.000
2  0.000  0.000  0.549  0.418  0.000  0.000  0.418  0.418     0.418

In [43]:
similarity = cosine_similarity(bow.iloc[[0,2]])

result = pd.DataFrame(similarity)
result

          0         1
0  1.000000  0.547723
1  0.547723  1.000000